Rb backend
ArturFariaVieira/projeto18-linkr-api pull request #1
Opened 2023-01-07 00:36 UTC by Ruytter

feat: connection db, sign-up, sign-in

2023-01-07 01:26 UTC, ArturFariaVieira approved these changes

2023-01-08 18:24 UTC, eduardaricaldes approved these changes

2023-01-09 04:50 UTC, ArturFariaVieira approved these changes

2023-01-09 18:15 UTC, eduardaricaldes requested changes

2023-01-09 18:15 UTC, eduardaricaldes commented on src/controllers/auth.controllers.js
> +    `SELECT * FROM users WHERE email = $1 `,
tudo que tem query sql tem que trocar para um repository, conforme foi pedido nos requisitos gerais da driven: [https://www.notion.so/bootcampra/Projeto-18-Projet-o-Linkr-0e4b709ec0f54ff39da37efbdb16c992](https://www.notion.so/bootcampra/Projeto-18-Projet-o-Linkr-0e4b709ec0f54ff39da37efbdb16c992)

# Requisitos gerais

- Tecnologias
    - [ ]  Front-end: utilize React e styled components
    - [ ]  Back-end: utilize Node, express, Postgres como banco
    - [ ]  Arquitetura back-end: utilize os padrões aprendidos de routers, controllers, schemas, repositories e middlewares

2023-01-09 18:16 UTC, eduardaricaldes commented on src/controllers/auth.controllers.js
> +    `SELECT * FROM users WHERE email = $1 `,
exemplo de como fiz: [https://github.com/eduardaricaldes/projeto17-shortly/blob/main/src/repositories/account.repository.js](https://github.com/eduardaricaldes/projeto17-shortly/blob/main/src/repositories/account.repository.js)

chamada no controller: [https://github.com/eduardaricaldes/projeto17-shortly/blob/main/src/controllers/account.controller.js](https://github.com/eduardaricaldes/projeto17-shortly/blob/main/src/controllers/account.controller.js)

2023-01-09 19:54 UTC, eduardaricaldes approved these changes

2023-01-09 20:01 UTC, merged